export const act_dic = {
  run: 'はしる',
  eat: 'をたべる',
  play: 'であそぶ',
  ride: 'にのる',
  cook: 'をりょうりする',
  getup: 'おきる',
  sleep: 'ねる',
  buy: 'をかう',
  practice: 'をりょうりする',
  watch: 'をみる',
  draw: 'をかく',
  make: 'をつくる',
  study: 'べんきょうする',
};
